MESSAGE_ROLE_REACTION = 808093027213770762
EASTER_EGGS = {
    "ping" : "PONG !",
    "thierry" : "Thierry ? C'est le boss en fait !",
    "dumartin" : "Thierry ? C'est le boss en fait !",
    "bernard" : "Eh OH révise tes Equa Diff !",
    "helly" : "Eh OH révise tes Equa Diff !",
    "sébastien" : "Sébastien ? Il fait des Opé Sponso CISCO !",
    "sebastien" : "Sébastien ? Il fait des Opé Sponso CISCO !",
    "mesure" : "Sébastien ? Il fait des Opé Sponso CISCO !",
    "c1sco" : "Bonjour, je suis C1SCO, un bot ECO + à votre service :)",
    "jpp" : "Vous avez demandé Jean Pierre Pernault ?",
    "magali" : "Jeunes gens, on ne parle pas comme ça de Magali !",
    "slingue" : "Jeunes gens, on ne parle pas comme ça de Magali !",
    "jamal" : "Linux c'est le sang",
    "khamlichi" : "Linux c'est le sang",
    "alain" : "Admirez mon magnifique Dr0n3",
    "gaugue" : "Admirez mon magnifique Dr0n3",
    "tanguy" : "Je manges mes cracottes et j'attend que passe mes études",
    "maths6" : "Plus meurtrier que la seconde guerre mondiale",
    "leo" : "Super Major is HERE !",
    "léo" : "Super Major is HERE !",
    "arnaud" : "I'm a bitch and a boss, I'm a shine like gloss",
    "michel" : "Rend ma clé privée wsh",
}
EMOJI_TO_ROLES = {
    "❤️" : "2015",
    "✈️" : "2016",
    "🙃" : "2017",
    "😎" : "2018",
    "😄" : "2019",
    "👓" : "2020",
    "🧂" : "2021",
    "🤡" : "2022"
}
